schema: https://api.kulturspektakel.de/graphql
documents:
  - ./pages/**/*.tsx
  - ./components/**/*.tsx
generates:
  ./types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
hooks:
  afterOneFileWrite:
    - prettier --write
