export default {
  slackClientID: process.env.REACT_APP_SLACK_CLIENT_ID,
  slackClientSecret: process.env.REACT_APP_SLACK_CLIENT_SECRET,
  googleSheet: process.env.REACT_APP_GOOGLE_SHEET,
  googleAPIKey: process.env.REACT_APP_GOOGLE_API_KEY,
  slackChannel: 'C3U99AB54',
  slackOldestMessage: 1564617600,
  slackBotID: 'BMEDF7M8B',
  genres: {
    Pop: '/pop.svg',
    Rock: '/rock.svg',
    Indie: '/acoustic.svg',
    'Hardrock / Metal / Punk': '/metal.svg',
    'Folk / Singer/Songwriter / Country': '/country.svg',
    'Elektro / Hip Hop': '/hip_hop.svg',
    DJ: '/disco.svg',
    'Reggae / Ska': '/hippie.svg',
    'Blues / Funk / Jazz / Soul': '/jazz.svg',
  },
  ratings: {
    one: 1,
    two: 2,
    three: 3,
    four: 4,
  },
  contactedEmoji: 'envelope_with_arrow',
  stars: ['', '★☆☆☆', '★★☆☆', '★★★☆', '★★★★'],
  colMapping: [
    'timestamp',
    'email',
    'bandname',
    'musikrichtung',
    'genre',
    'wohnort',
    'facebook',
    'demo',
    'website',
    'beschreibung',
    'mitglieder',
    'mitglieder-nonmal',
    'anreise',
    'name',
    'handy',
    'woher',
    'aufmerksam',
    'entfernung',
    'likes',
  ],
};
